# Generated by Django 3.0.3 on 2020-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200415_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ImageField(upload_to='items'),
        ),
    ]
