# Generated by Django 3.0.3 on 2020-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200416_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
