# Generated by Django 3.0.3 on 2020-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200424_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=5, null=True),
        ),
    ]
