# Generated by Django 3.0.3 on 2020-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200416_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
