# Generated by Django 3.0.3 on 2020-04-25 09:05

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200424_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.ImageField(upload_to='items', validators=[items.models.file_size]),
        ),
    ]
